services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./test_stuff
    ports:
      - "5173:5173"