services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HTTP_PROXY=http://110.136.114.93:8080
      - HTTPS_PROXY=http://110.136.114.93:8080
      - http_proxy=http://110.136.114.93:8080
      - https_proxy=http://110.136.114.93:8080

  frontend:
    build:
      context: ./test_stuff
    ports:
      - "5173:5173"
    volumes:
      - ./test_stuff:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
