services:
  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HTTP_PROXY=user235092:ws16r4@176.101.58.200:2095
      - HTTPS_PROXY=user235092:ws16r4@176.101.58.200:2095
      - http_proxy=user235092:ws16r4@176.101.58.200:2095
      - https_proxy=user235092:ws16r4@176.101.58.200:2095

  frontend:
    build:
      context: ./test_stuff
    ports:
      - "5173:5173"
    volumes:
      - ./test_stuff:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']
