name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - tests
  pull_request:
    branches:
      - main
      - master
      - tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python installing
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # или другая версия, которая у вас используется

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Unit tests run
        run: |
          pytest --maxfail=1 --disable-warnings --tb=short --html=unit_tests_report.html --self-contained-html tests/unit_tests1.py

      - name: Integration tests run
        run: |
          pytest --maxfail=1 --disable-warnings --tb=short --html=integration_tests_report.html --self-contained-html api/integration_tests.py

      - name: Report generation
        run: |
          mkdir -p reports
          cp unit_tests_report.html reports/
          cp integration_tests_report.html reports/
          

      - name: Reports archiving
        uses: actions/upload-artifact@v4
        with:
          name: tests reports
          path: reports/
